export const SET_TAG = 'SET_TAG';
export const SET_SELECTED_TAGS = 'SET_SELECTED_TAGS';
export const LOADED_JOBS = 'LOADED_JOBS';
export const REQUEST_JOBS = 'REQUEST_JOBS';
export const LOADED_JOB_DETAIL = 'LOADED_JOB_DETAIL';